name: MicroKits
version: '${project.version}'
main: me.paradis.microkits.MicroKits
api-version: 1.18
authors: [ Paradis ]
description: a clickable kit system for servers
commands:
  microkits:
    description: manage micro kits
    usage: /[microkits|mk] [new|edit] [name]
